"use server";
import { revalidatePath, revalidateTag } from "next/cache";
import { FieldValue } from "firebase-admin/firestore";
import { requireAdmin } from "@/lib/auth";
import { adminDb, isFirebaseConfigured } from "@/lib/firebase-admin";

const allowedCollections=new Set(["projects","services","certifications","experiences","recommendations"]);
function strings(form:FormData,name:string){return String(form.get(name)??"").split("\n").map(x=>x.trim()).filter(Boolean)}
export async function saveContent(form:FormData){await requireAdmin();if(!isFirebaseConfigured)throw new Error("Firebase Admin credentials are required.");const collection=String(form.get("collection"));if(!allowedCollections.has(collection))throw new Error("Unsupported collection.");const id=String(form.get("id")||form.get("slug")||crypto.randomUUID()).trim();if(!/^[a-z0-9-]+$/.test(id))throw new Error("ID must use lowercase letters, numbers and hyphens.");const data:Record<string,unknown>={};for(const [key,value] of form.entries()){if(["collection","id"].includes(key))continue;if(["stack","decisions","deliverables","proofProjectSlugs","serviceSlugs"].includes(key))data[key]=strings(form,key);else if(["published","featured","enabled","permissionConfirmed"].includes(key))data[key]=value==="on";else if(["sortOrder"].includes(key))data[key]=Number(value)||999;else data[key]=String(value).trim()}data.updatedAt=FieldValue.serverTimestamp();await adminDb.collection(collection).doc(id).set(data,{merge:true});revalidateTag(collection,"max");revalidatePath("/", "layout");}
export async function deleteContent(form:FormData){await requireAdmin();const collection=String(form.get("collection"));const id=String(form.get("id"));if(!allowedCollections.has(collection)||!id)throw new Error("Invalid delete request.");await adminDb.collection(collection).doc(id).delete();revalidateTag(collection,"max");revalidatePath("/", "layout");}
export async function updateLeadStatus(form:FormData){await requireAdmin();const id=String(form.get("id"));const status=String(form.get("status"));if(!id||!["new","contacted","won","lost"].includes(status))throw new Error("Invalid lead update.");await adminDb.collection("leads").doc(id).update({status,updatedAt:FieldValue.serverTimestamp()});revalidatePath("/admin/leads")}
