import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ProjectCard } from "@/components/cards";
import { getProjects, getService, getServices } from "@/lib/data";
import { absoluteUrl } from "@/lib/site";
export async function generateStaticParams(){return (await getServices()).map(s=>({slug:s.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const s=await getService(slug);return s?{title:s.seoTitle??s.title,description:s.metaDescription??s.description,alternates:{canonical:`/services/${s.slug}`}}:{}}
export default async function ServicePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const [service,allProjects]=await Promise.all([getService(slug),getProjects()]);if(!service)notFound();const proof=allProjects.filter(p=>service.proofProjectSlugs.includes(p.slug));if(proof.length===0)notFound();const schema={"@context":"https://schema.org","@type":"Service",name:service.title,description:service.description,provider:{"@id":`${absoluteUrl("/")}#person`},url:absoluteUrl(`/services/${service.slug}`)};return <main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><section className="service-detail-hero container"><div><div className="breadcrumb"><Link href="/services">Services</Link><span>/</span><span>{service.title}</span></div><div className="eyebrow">Service {String(service.sortOrder).padStart(2,"0")}</div><h1>{service.title}</h1><p>{service.description} Built for {service.audience.toLowerCase()}.</p><Link className="button primary" href={`/contact?service=${service.slug}`}>Start a project</Link></div><div className="service-schematic"><span>INPUT</span><i/><strong>{service.title.toUpperCase()}</strong><i/><span>WORKING OUTPUT</span></div></section><section className="container service-detail-grid"><div><div className="section-header"><div><div className="eyebrow">Deliverables</div><h2>What you get</h2></div></div><ul className="deliverables">{service.deliverables.map(x=><li key={x}>{x}</li>)}</ul></div><div><div className="section-header"><div><div className="eyebrow">Boundaries</div><h2>Scope and limitations</h2></div></div><p>{service.limitations}</p><div className="badges">{service.stack.map(x=><span className="badge" key={x}>{x}</span>)}</div></div></section><section className="section container"><div className="section-header"><div><div className="eyebrow">Proof</div><h2>Projects behind the claim</h2></div></div><div className="project-grid">{proof.map(p=><ProjectCard key={p.id} project={p}/>)}</div></section></main>}
