import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ProjectVisual } from "@/components/cards";
import { getProject, getProjects, getServices } from "@/lib/data";
import { absoluteUrl } from "@/lib/site";
export async function generateStaticParams(){return (await getProjects()).map(p=>({slug:p.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=await getProject(slug);if(!p)return{};return{title:p.seoTitle??p.title,description:p.metaDescription??p.summary,alternates:{canonical:`/projects/${p.slug}`},openGraph:{title:p.title,description:p.summary,type:"article"}}}
export default async function ProjectPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const [p,services]=await Promise.all([getProject(slug),getServices()]);if(!p)notFound();const related=services.filter(s=>p.serviceSlugs.includes(s.slug));const schema={"@context":"https://schema.org","@graph":[{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Projects",item:absoluteUrl("/projects")},{"@type":"ListItem",position:2,name:p.title}]},{"@type":"SoftwareSourceCode",name:p.title,description:p.summary,codeRepository:p.repositoryUrl,programmingLanguage:p.stack,creativeWorkStatus:p.status,author:{"@id":`${absoluteUrl("/")}#person`}}]};return <main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><section className="case-hero container"><div className="breadcrumb"><Link href="/projects">Projects</Link><span>/</span><span>{p.title}</span></div><div className="badges"><span className="badge type">{p.projectType}</span><span className="badge">{p.status}</span></div><h1>{p.title}</h1><p>{p.summary}</p><ProjectVisual project={p}/></section><section className="container case-layout"><article className="case-body"><Case n="01" title="The problem"><p>{p.problem}</p></Case><Case n="02" title="What I built"><p>{p.built}</p></Case><Case n="03" title="Architecture"><pre className="architecture">{p.architecture}</pre></Case><Case n="04" title="Key engineering decisions"><ul>{p.decisions.map(d=><li key={d}>{d}</li>)}</ul></Case><Case n="05" title="What it demonstrates"><p>{p.outcome}</p></Case><Case n="06" title="Lessons learned"><p>{p.lessons}</p></Case><Case n="07" title="Limitations"><p>{p.limitations}</p></Case><Case n="08" title="What I would improve next"><p>{p.improvements}</p></Case>{related.length>0&&<Case n="09" title="Related services"><div className="badges">{related.map(s=><Link key={s.id} className="badge" href={`/services/${s.slug}`}>{s.title}</Link>)}</div></Case>}</article><aside className="case-aside"><div className="eyebrow">At a glance</div><div><span>Built for</span><strong>{p.audience}</strong></div><div><span>Stack</span><div className="badges">{p.stack.map(s=><span className="badge" key={s}>{s}</span>)}</div></div>{p.demoUrl&&<a className="button primary" href={p.demoUrl} target="_blank" rel="noopener noreferrer">Live demo</a>}{p.repositoryUrl&&<a className="button secondary" href={p.repositoryUrl} target="_blank" rel="noopener noreferrer">View code</a>}<Link className="button secondary" href={`/contact?service=${p.serviceSlugs[0]??"other"}`}>Start something similar</Link></aside></section></main>}
function Case({n,title,children}:{n:string;title:string;children:React.ReactNode}){return <section className="case-section"><span className="case-number">{n}</span><h2>{title}</h2>{children}</section>}
