import type { Certification, Experience, Project, Recommendation, Service, SiteProfile } from "./types";

export const profile: SiteProfile = {
  name: "Rehan Mehmood", title: "AI + Full-Stack Engineer", location: "Lahore, Punjab, Pakistan",
  email: "mehmoodrehan708@gmail.com", whatsapp: "923288514952", github: "https://github.com/rehan-mehmood-tech", linkedin: "https://www.linkedin.com/in/rehan-mehmood",
  availability: "Open to AI, backend and full-stack internships and junior roles, and scoped freelance projects.",
  positioning: "Rehan Mehmood is an AI + Full-Stack Engineer in Lahore, Pakistan. He builds AI agents, workflow automations and the backend APIs behind them using LangGraph, FastAPI, Node.js and Next.js.",
  bio: "I build agents that call real tools and the backend systems those agents depend on. I focus on clear system boundaries, visible failure states and maintainable handoffs.",
  education: "BS Computer Science, University of Management and Technology (Mar 2024 â€“ Mar 2028)",
  photoUrl: "/images/rehan-mehmood-portrait.png",
  stack: { AI: "LangGraph, LangChain, Groq, tool calling, multi-agent orchestration", Backend: "Python, FastAPI, Node.js, Express, REST APIs", Data: "Firebase and Firestore", Automation: "n8n, webhooks, API integrations", Frontend: "Next.js, React, TypeScript, Tailwind CSS", Tooling: "Git, GitHub, Vercel, Render" },
};

export const projects: Project[] = [
  { id:"multi-agent-startup-platform", slug:"multi-agent-startup-platform", title:"Multi-Agent AI Startup Launch Platform", projectType:"Capstone (AI Seekho)", category:"AI agents", summary:"Five LangGraph agents turn a startup idea into a structured pitch with tool use, orchestration and human-in-the-loop review.", audience:"Founders exploring a new product idea", problem:"Early product research, positioning and planning are fragmented across disconnected tasks.", built:"A coordinated system of market research, product strategy, pricing, marketing and orchestrator agents.", architecture:"Next.js client â†’ FastAPI API â†’ LangGraph orchestrator â†’ specialist agents and Groq â†’ Supabase persistence.", decisions:["Used a supervisor graph to make handoffs explicit.","Kept pricing calculations in tools rather than model arithmetic.","Added human review before final output."], outcome:"A working capstone prototype defended to an industry panel.", lessons:"Agent boundaries and state contracts matter more than adding more prompts.", limitations:"The current deployment is a prototype and has not been load-tested.", improvements:"Add evaluation traces, retry policies and richer persistence.", stack:["Next.js","TypeScript","FastAPI","LangGraph","Groq","Supabase"], demoUrl:"https://aistartuplaunchteam-a0peaiexa-mehmoodrehan708-5335s-projects.vercel.app", repositoryUrl:"https://github.com/rehan-mehmood-tech/AI-Startup-Launch-team", published:true, featured:true, sortOrder:1, status:"Prototype", serviceSlugs:["ai-agent-development","custom-software-backend"] },
  { id:"erythronet", slug:"erythronet", title:"ErythroNet â€” Emergency Blood Donation Network", projectType:"Course project (AI Seekho)", category:"Full-stack", summary:"Connects blood donors with patients through a live request board and area-targeted push alerts.", audience:"Blood donors, patients and coordinators", problem:"Urgent donation requests are difficult to route quickly to relevant nearby donors.", built:"A full-stack request workflow with notifications and a hardened Express API.", architecture:"React client â†’ Express API â†’ Firestore â†’ Firebase Cloud Messaging.", decisions:["Used Firestore for real-time request updates.","Applied rate limiting, Helmet and restricted CORS.","Targeted notifications by donor area."], outcome:"A working course project demonstrating an end-to-end emergency request workflow.", lessons:"Notification reliability and abuse controls must be designed together.", limitations:"Real-world operation would require identity verification and organizational partnerships.", improvements:"Add verified organizations, delivery monitoring and operational dashboards.", stack:["React","TypeScript","Node.js","Express","Firestore","FCM"], published:true, featured:true, sortOrder:2, status:"Course project", serviceSlugs:["custom-software-backend"] },
  { id:"qsr-customer-service-agent", slug:"qsr-customer-service-agent", title:"QSR Customer-Service Agent", projectType:"Independent demo (AKTI)", category:"AI agents", summary:"A ReAct agent that searches, looks up branches, calculates bills and logs complaints by email. Not affiliated with any company.", audience:"Quick-service restaurant support teams", problem:"Repetitive support questions span location, order and complaint workflows.", built:"A tool-calling assistant with search, calculation and email tools.", architecture:"Streamlit UI â†’ LangGraph ReAct agent â†’ Groq â†’ SerpAPI and email tools.", decisions:["Kept business actions in allowlisted tools.","Used a ReAct loop for observable tool selection.","Clearly labelled the build as an independent demo."], outcome:"A working training demo covering multiple customer-service intents.", lessons:"Tool descriptions and failure messages strongly affect agent reliability.", limitations:"It is not connected to a real restaurant system.", improvements:"Add business-owned data, authentication and evaluation conversations.", stack:["LangGraph","LangChain","Groq","SerpAPI","Streamlit"], published:true, featured:true, sortOrder:3, status:"Independent demo", serviceSlugs:["ai-agent-development","ai-chatbot-development"] },
  { id:"n8n-ai-automation-workflows", slug:"n8n-ai-automation-workflows", title:"n8n AI Customer-Service Agent & Integration Workflows", projectType:"Course projects", category:"Automation", summary:"An n8n agent with memory and API tools, plus integration pipelines with batching, authentication and error workflows.", audience:"Small teams connecting repetitive processes", problem:"Manual transfers between tools are slow and failures often remain invisible.", built:"Reusable automation workflows covering APIs, webhooks, batching and explicit error paths.", architecture:"Webhook or schedule â†’ n8n workflow â†’ authenticated APIs â†’ data table and notifications.", decisions:["Added dedicated error branches.","Used batching for bounded API processing.","Kept credentials in n8n credential storage."], outcome:"Working n8n Academy and AI Seekho course workflows.", lessons:"Operational visibility is as important as the happy path.", limitations:"Each deployment still requires client-specific credentials and validation.", improvements:"Add reusable monitoring, alerting and deployment documentation.", stack:["n8n","Groq","REST APIs","Webhooks"], published:true, featured:true, sortOrder:4, status:"Course project", serviceSlugs:["ai-automation"] },
  { id:"skill-forge", slug:"skill-forge", title:"Skill-Forge â€” AI Career Assistant", projectType:"Hackathon prototype", category:"Full-stack", summary:"Skill assessment and roadmap generation with an agentic assistant, built during a 24-hour hackathon.", audience:"Learners planning a technical career path", problem:"Generic learning advice does not adapt to a learnerâ€™s current skills and goals.", built:"A rapid prototype combining assessment, roadmap generation and conversational guidance.", architecture:"Next.js client â†’ FastAPI â†’ LangChain and LangGraph â†’ Groq.", decisions:["Prioritized a complete narrow flow for the time limit.","Separated assessment state from chat state.","Labelled unverified product claims as out of scope."], outcome:"A functioning 24-hour hackathon prototype with known rough edges.", lessons:"Time-boxing demands ruthless prioritization of one coherent journey.", limitations:"The recommendation quality has not been formally evaluated.", improvements:"Add grounded curriculum sources, evaluation and persistent progress.", stack:["Next.js","FastAPI","LangChain","LangGraph","Groq"], demoUrl:"https://skillforge-nine-liard.vercel.app", published:true, featured:true, sortOrder:5, status:"Prototype", serviceSlugs:["ai-agent-development"] },
  { id:"awaz-e-fard", slug:"awaz-e-fard", title:"Awaz-e-Fard â€” Anonymous Reporting Platform", projectType:"Course project (AI Seekho)", category:"Full-stack", summary:"Anonymous reporting for transgender and gender-diverse communities with client-side token hashing, Row-Level Security and a bilingual UI.", audience:"People who need a privacy-conscious reporting channel", problem:"Sensitive reports require anonymity without losing the ability to follow progress.", built:"A bilingual reporting flow using locally derived tokens and database policies.", architecture:"Next.js client â†’ Supabase API â†’ PostgreSQL with Row-Level Security.", decisions:["Hashed tracking tokens in the browser.","Applied Row-Level Security to every data path.","Designed the interface for English and Urdu."], outcome:"A working privacy-focused course project.", lessons:"Privacy claims must be supported by concrete data-flow decisions.", limitations:"It requires a formal threat model and independent security review before real-world use.", improvements:"Add professional security testing and partner-led moderation workflows.", stack:["Next.js","Supabase","Web Crypto API","Tailwind CSS"], published:true, featured:false, sortOrder:6, status:"Course project", serviceSlugs:["custom-software-backend"] },
  { id:"cricmetrics-pk", slug:"cricmetrics-pk", title:"CricMetrics-PK â€” Cricket Analytics Dashboard", projectType:"Course project (AI Seekho)", category:"Frontend", summary:"Phase-wise player analytics, comparison radars and a scenario-based squad builder rendered with the native Canvas API.", audience:"Cricket viewers exploring player comparisons", problem:"Raw match statistics are difficult to compare across phases and roles.", built:"An interactive dashboard and squad-building interface without a frontend framework.", architecture:"Browser application â†’ local structured datasets â†’ Canvas 2D visualizations.", decisions:["Used Canvas for custom radar visualizations.","Kept the build framework-free to strengthen browser fundamentals.","Separated comparison and squad scenarios."], outcome:"A working interactive course dashboard.", lessons:"Visualization labels and comparison context matter as much as the chart itself.", limitations:"The data pipeline is not live.", improvements:"Connect a reliable cricket-data source and add accessible table alternatives.", stack:["HTML5","CSS3","JavaScript","Canvas 2D API"], published:true, featured:false, sortOrder:7, status:"Course project", serviceSlugs:[] },
  { id:"automotive-buying-assistant", slug:"automotive-buying-assistant", title:"Automotive Buying Assistant", projectType:"Independent demo (AKTI)", category:"AI agents", summary:"A conversational assistant for car buyers that keeps history and adapts to English or Roman Urdu. Not affiliated with any company.", audience:"Car buyers comparing options", problem:"Buyers need a conversational way to narrow choices while retaining preferences.", built:"A bilingual conversational assistant with session history.", architecture:"Streamlit UI â†’ LangChain conversation layer â†’ Groq.", decisions:["Preserved conversation history per session.","Supported Roman Urdu alongside English.","Removed third-party brand affiliation."], outcome:"A working independent training demo.", lessons:"Language flexibility improves usability but needs structured evaluation.", limitations:"Recommendations are not grounded in a live verified inventory.", improvements:"Connect verified listings and add transparent recommendation criteria.", stack:["LangChain","Groq","Streamlit"], published:true, featured:false, sortOrder:8, status:"Independent demo", serviceSlugs:["ai-chatbot-development"] },
];

export const services: Service[] = [
  { id:"ai-agent-development",slug:"ai-agent-development",title:"AI Agents & Multi-Agent Workflows",description:"Agents that call your APIs, search, calculate and hand off to a human when it matters.",audience:"Teams with multi-step knowledge or decision workflows",deliverables:["Written scope and system boundaries","Working agent workflow","Tool and fallback handling","Source code and handoff notes"],stack:["LangGraph","LangChain","Groq"],limitations:"Production integrations, hosting and evaluation scope are confirmed separately.",proofProjectSlugs:["multi-agent-startup-platform","qsr-customer-service-agent"],enabled:true,sortOrder:1 },
  { id:"ai-chatbot-development",slug:"ai-chatbot-development",title:"AI Chatbots & Customer-Support Agents",description:"Website and support assistants that answer from your data and capture qualified leads.",audience:"Small teams handling repetitive questions",deliverables:["Conversation map","Working assistant","Approved integrations","Lead capture and handoff"],stack:["LangGraph","FastAPI","Groq"],limitations:"The assistant only receives access to approved business data and tools.",proofProjectSlugs:["qsr-customer-service-agent"],enabled:true,sortOrder:2 },
  { id:"ai-automation",slug:"ai-automation",title:"Business Process Automation (n8n)",description:"Pipelines that connect your tools through APIs and webhooks, with error handling so failures surface.",audience:"Teams moving information between tools by hand",deliverables:["Workflow map","n8n implementation","Error branches","Setup and ownership notes"],stack:["n8n","REST","Webhooks"],limitations:"Third-party service fees and unsupported private APIs are outside the base scope.",proofProjectSlugs:["n8n-ai-automation-workflows"],enabled:true,sortOrder:3 },
  { id:"custom-software-backend",slug:"custom-software-backend",title:"Custom Software & Backend Systems",description:"FastAPI or Node.js APIs with authentication and Firestore, plus a Next.js interface when needed.",audience:"Teams that need a scoped operational application",deliverables:["System scope","API and data model","Working application","Deployment and handoff"],stack:["FastAPI","Node.js","Next.js","Firestore"],limitations:"Scale, compliance and uptime commitments require explicit discovery and testing.",proofProjectSlugs:["multi-agent-startup-platform","erythronet","awaz-e-fard"],enabled:true,sortOrder:4 },
];

export const certifications: Certification[] = [
  {id:"ai-seekho",name:"Artificial Intelligence & Emerging Technologies Training Program",issuer:"UMT Inter AI Club",date:"Sep 2026",published:true,sortOrder:1},
  {id:"n8n-103",name:"N8N103 In Practice: AI, Testing & Best Practices",issuer:"n8n",date:"Date pending",published:true,sortOrder:2},
  {id:"n8n-102",name:"N8N102 Integrations: APIs & Connected Workflows",issuer:"n8n",date:"Date pending",published:true,sortOrder:3},
  {id:"n8n-essentials",name:"n8n Essentials: Your First Workflows",issuer:"n8n",date:"Date pending",published:true,sortOrder:4},
  {id:"n8n-quickstart",name:"n8n Quickstart",issuer:"n8n",date:"Date pending",published:true,sortOrder:5},
  {id:"developershub",name:"Certificate of Completion â€” Full Stack Development Internship",issuer:"DevelopersHub Corporation",date:"Jun 2026",published:true,sortOrder:6},
];
export const experiences: Experience[] = [
  {id:"developershub",role:"Full Stack Development Intern",organization:"DevelopersHub Corporation",location:"Remote",startDate:"2026",endDate:"Jun 2026",summary:"Built and practiced full-stack application workflows during a structured internship.",type:"Internship",published:true,sortOrder:1},
  {id:"ai-seekho",role:"AI Seekho Program Trainee",organization:"UMT Inter AI Club",location:"Lahore",startDate:"2026",endDate:"Sep 2026",summary:"Completed an AI and emerging technologies program and defended a multi-agent capstone to an industry panel.",type:"Training",published:true,sortOrder:2},
  {id:"umt",role:"BS Computer Science",organization:"University of Management and Technology",location:"Lahore",startDate:"Mar 2024",endDate:"Mar 2028",summary:"Computer Science undergraduate focused on AI systems, backend development and full-stack engineering.",type:"Education",published:true,sortOrder:3},
];
export const recommendations: Recommendation[] = [{id:"umair-khan",name:"Umair Khan",role:"AI Consultant, Agentic AI Engineer",relationship:"Teacher, AI Seekho",quote:"Rehan is a motivated learner who is understanding full-stack web application architecture and agentic AI concepts very well. He shows strong technical learning, problem-solving and responsibility for his code and achievements.",permissionConfirmed:false,published:false}];
