"use client";
import { FormEvent, useEffect, useRef, useState } from "react";
import { Icon } from "./icons";
type Line={kind:"system"|"user"|"agent";text:string};
export function Terminal(){const [open,setOpen]=useState(false);const [max,setMax]=useState(false);const [value,setValue]=useState("");const [busy,setBusy]=useState(false);const [lines,setLines]=useState<Line[]>([{kind:"system",text:"Rehan AI Agent — answers can be imperfect. Do not share sensitive information."}]);const output=useRef<HTMLDivElement>(null);const trigger=useRef<HTMLButtonElement>(null);
useEffect(()=>output.current?.scrollTo({top:output.current.scrollHeight}),[lines]);
useEffect(()=>{if(!open)return;const key=(e:KeyboardEvent)=>{if(e.key==="Escape"){setOpen(false);trigger.current?.focus()}};addEventListener("keydown",key);return()=>removeEventListener("keydown",key)},[open]);
async function run(message:string){const text=message.trim();if(!text||busy)return;if(text==="clear"){setLines([]);setValue("");return}setLines(v=>[...v,{kind:"user",text}]);setValue("");setBusy(true);try{const res=await fetch(`${process.env.NEXT_PUBLIC_AGENT_API_URL??"http://localhost:8000"}/chat`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({session_id:sessionStorage.getItem("chat_session")??crypto.randomUUID(),message:text})});if(!res.ok||!res.body)throw new Error();const reader=res.body.getReader();const decoder=new TextDecoder();let answer="";setLines(v=>[...v,{kind:"agent",text:""}]);while(true){const {done,value}=await reader.read();if(done)break;const chunk=decoder.decode(value,{stream:true});for(const block of chunk.split("\n\n")){const data=block.split("\n").find(line=>line.startsWith("data: "))?.slice(6);if(!data)continue;try{const event=JSON.parse(data);if(event.t){answer+=event.t;setLines(v=>[...v.slice(0,-1),{kind:"agent",text:answer}])}}catch{}}}}catch{setLines(v=>[...v,{kind:"agent",text:"The assistant is offline right now. Use the contact form or email Rehan directly."}])}finally{setBusy(false)}}
if(!open)return <button ref={trigger} className="terminal-launcher" onClick={()=>setOpen(true)}><span>&gt;_ ask rehan&apos;s agent</span><i>▍</i></button>;
return <div className={`terminal-window ${max?"maximized":""}`} role="dialog" aria-modal="true" aria-label="Rehan's AI assistant"><div className="terminal-title"><span><Icon name="terminal" size={15}/> Command Prompt — Rehan AI Agent</span><div><button onClick={()=>setMax(!max)} aria-label={max?"Restore":"Maximize"}>□</button><button onClick={()=>{setOpen(false);trigger.current?.focus()}} aria-label="Close"><Icon name="close" size={14}/></button></div></div><div className="terminal-output" ref={output} aria-live="polite">{lines.map((line,index)=><p key={index} className={line.kind}>{line.kind==="user"&&<strong>guest&gt; </strong>}{line.kind==="agent"&&<strong>rehan-ai&gt; </strong>}{line.text}</p>)}{busy&&<p className="system">connecting / streaming…</p>}</div><div className="command-chips">{["services","projects","availability","contact"].map(c=><button key={c} onClick={()=>run(c)}>{c}</button>)}</div><form className="terminal-input" onSubmit={(e:FormEvent)=>{e.preventDefault();void run(value)}}><label htmlFor="terminal-command">guest&gt;</label><input id="terminal-command" autoFocus value={value} onChange={e=>setValue(e.target.value)} maxLength={1000}/><span>▍</span></form></div>}
